name: Build and Publish Signed APK

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Extract Version Name
        id: get_version
        run: |
          version=$(grep 'version=' version.properties | cut -d'=' -f2)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build Signed Release APK
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASS }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/release/SFL-Notifi.apk
          asset_name: SFL-Notifi.apk
          asset_content_type: application/vnd.android.package-archive
